### ISSUE TITLE
How to test an image is normal or abnomal? 

### ISSUE THREAD

**Issue by zhaobingbingbing** [tkwoo/anogan-keras#4]
Hi,
Thans for your work. I have a question about after train progress. When we send abnoamal image to the model, it can only give a abnomal score, but how can we make sure model classify this image as nomal or abnomal? And I noticed in paper, there are some evaluation index for model ,such as precision,recall,AUC and so on ,how to realize this fuction?
Thanks again for your kind reply.

**Comment by tkwoo** [comment]
I think 'abnormal score' can be used to classify.
We can make 'threshold value of abnormal score' on our training(validation) dataset.
You should decide threshold value to maximize precision, recall on you dataset.

Abnormal area can be also used abnormal score.

Thank you.
